name: SBCL Collector

on:
  workflow_dispatch: {}
  schedule:
    # Avvia ogni 6 ore (00:00, 06:00, 12:00, 18:00 UTC)
    - cron: "0 */6 * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 355  # 5h55m (GitHub max ≈ 6h)
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # 👇 FIX: se c'è package-lock usa npm ci, altrimenti npm install
      - name: Install deps
        run: |
          if [ -f package-lock.json ]; then
            echo "Using npm ci"
            npm ci --omit=dev
          else
            echo "Using npm install (no package-lock.json found)"
            npm install --omit=dev
          fi

      - name: Start collector (keep alive)
        run: |
          node collector.js &
          PID=$!
          echo "Collector PID: $PID"
          # Mantieni vivo il job per 355 minuti
          for i in $(seq 1 355); do
            echo "tick $i"
            sleep 60
          done
          echo "Stopping..."
          kill $PID || true
